### PR TITLE
serve as SPA from the node webserver

### PR DESCRIPTION
**Pull request by folkertdev**
Just making a PR for this already so we can track progress here. 

actionable items

* reroute all top-level urls to /index.html

general questions

* where do we put resources (js/css/images)?
* can we integrate compiling elm into the node server (e.g. recompile when starting)? 

<hr>

to test this, you need to compile elm into js and put it in the correct position. This can be done by

```sh
elm-make src/Main.elm --output=index.js; mv index.js ../backend/public_html/
```
(make sure you run this from `/frontend`)

### CODE REVIEW

**Comment by dennis-school** [comment]
Actionable items - Questions:

- Regarding presenting `index.html`: I suppose anything except the files that are in `public_html` (`style.css`, `script.js`, etc.) or endpoints in `/api/` should present `index.html`. Correct?

Answering general questions:

- All resources can be put in `public_html` (in `backend`), as these will be statically served to the client.
- I will integrate elm-compilation with the Node server

**Comment by folkertdev** [comment]
regarding your question: yes

**Comment by dennis-school** [comment]
In `public_html`, `index.js` is automatically generated on every manual server restart.
All other resources in `public_html` persist, so those can be put in there (css/js/images)

Problem: When accessing the webpage on the Node server's address (`http://localhost:8080/*`), whenever a link is clicked (e.g. 'Attribution' or 'Profiling'), the page still refreshes.

**Comment by folkertdev** [comment]
regarding the problem: weird. it doesn't on chrome, but does on firefox. I'll look into it. 

for the rest: great. I'll extract the css into a separate file, and then I think we can merge this into development

**Comment by folkertdev** [comment]
@dennis-school  this is now ready for review

**Comment by dennis-school** [comment]
Some `<a>` tags no longer have the `href='#'`.
`<a>` tags need a `href` attribute, otherwise browsers don't enable a pointer-cursor. Because it is then not really a link.

**Comment by dennis-school** [comment]
Yeah, agree. Never do it with CSS.

But if we are going to `preventDefault` it anyway, might as well give them meaningful links.
So users see an actual URL in the lower-left corner, instead of a `#`.

**Review by dennis-school — APPROVED** [review]
Everything is added.
Works in Firefox and Chrome, under Windows and Linux.

**Pull request merged**
