### PR TITLE
Feature new design

### PR DESCRIPTION
**Pull request by folkertdev**
*DO NOT MERGE YET!*

So, this branch will implement the new design we have, but as a consequence we also have to make some architecture adjustments. This was inevitable at some point anyway, so here we are. 

This is heavily inspired on [this SPA example](https://github.com/rtfeldman/elm-spa-example), in particular its routing, module layout and a trick to add (custom) loading markup.

### CODE REVIEW

**Comment by dennis-school** [comment]
Merge conflicts. This branch is messed up now. Will fix after demo's. (Don't want to risk losing local style-updated copy)

**Comment by dennis-school** [comment]
Also, issue: Navigation is behaving weirdly. ('/#/attribution' is attribution page. '/attribution' is not)

**Comment by folkertdev** [comment]
that is not an issue, it is how SPA navigation is (meant to) work. Everything after the #  is seen as a local change, so it won't ever trigger a reload from the server. This is much nicer than having to add a preventDefault and preventPropagation to every link.

**Comment by dennis-school** [comment]
URLs are supposed to be meaningful, and easily rememberable and recognizable by users. The '#' clutters this. Hence, it is an issue IMO. (Even if it makes the code a (very little) bit more complex)

**Comment by folkertdev** [comment]
do you really remember full urls? 

Anyway, this is how SPA routing is supposed to work. Google it; angular, react, even jquery (wtf, really) does this.

**Comment by dennis-school** [comment]
Initially, the explanation text in the attribution header "The Authorship Attribution ... by the same person." had the word 'unknown' written in italic, because this was also done in the paper we received. (As a form of emphasising it) Using `I18n` this does not seem possible, because any hardcoded HTML is escaped.

**Comment by dennis-school** [comment]
@folkertdev Regarding the URLs: I still think clear URLs are more important than some arbitrary convention.

(Also, because in our current state an URL like `/attribution-lorem-ipsum#/attribution` is accepted as the attribution page, which is ridiculous)

**Review by dennis-school — APPROVED** [review]
Seems good enough.

**Pull request merged**
